AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/ExpandPathArguments:
    Enabled: false

Style/SpecialGlobalVars:
    Enabled: false

Style/SymbolProc:
    Enabled: false

Style/Semicolon:
    Enabled: false

Layout/ExtraSpacing:
    Enabled: false

Layout/BlockAlignment:
    Enabled: false

Metrics/MethodLength:
    Max: 15
