AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/SymbolProc:
    Enabled: false

Metrics/MethodLength:
    Max: 15

Gemspec/DevelopmentDependencies:
    Enabled: false
