AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/SpecialGlobalVars:
    Enabled: false
    